import {
  IconAlertTriangle,
  IconArticle,
  IconBell,
  IconBook,
  IconBox,
  IconCalendar,
  IconGavel,
  IconPackages,
  IconReceipt,
  IconUsers,
} from "@tabler/icons-react";

export const sidebar = [
  {
    descripcion: "Unidad",
    posicion: 1,
    colorFondo: "",
    titulo: "UNIDAD",
    iconoWeb: <IconBox width={22} height={22} />,
    url: "",
  },
  {
    descripcion: "Reservas",
    posicion: 1,
    colorFondo: "",
    titulo: "RESERVAS",
    iconoWeb: <IconCalendar width={22} height={22} />,
    url: "/reservas",
  },
  {
    descripcion: "Reclamos",
    posicion: 1,
    colorFondo: "",
    titulo: "RECLAMOS",
    iconoWeb: <IconAlertTriangle width={22} height={22} />,
    url: "/reclamos",
  },
  {
    descripcion: "Pagos",
    posicion: 1,
    colorFondo: "",
    titulo: "PAGOS",
    iconoWeb: <IconReceipt width={22} height={22} />,
    url: "/pagos",
  },
  {
    descripcion: "Novedades",
    posicion: 1,
    colorFondo: "",
    titulo: "NOVEDADES",
    iconoWeb: <IconBell width={22} height={22} />,
    url: "/novedades",
  },
  {
    descripcion: "Juicios",
    posicion: 1,
    colorFondo: "",
    titulo: "JUICIOS",
    iconoWeb: <IconGavel width={22} height={22} />,
    url: "/juicios",
  },
  {
    descripcion: "Asambleas",
    posicion: 1,
    colorFondo: "",
    titulo: "ASAMBLEAS",
    iconoWeb: <IconUsers width={22} height={22} />,
    url: "/asambleas",
  },
  {
    descripcion: "Reglamento",
    posicion: 1,
    colorFondo: "",
    titulo: "REGLAMENTO",
    iconoWeb: <IconBook width={22} height={22} />,
    url: "/reglamento",
  },
  {
    descripcion: "Todas las unidades",
    posicion: 1,
    colorFondo: "",
    titulo: "TODAS LAS UNIDADES",
    iconoWeb: <IconPackages width={22} height={22} />,
    url: "/prp/expensas",
  },
];

export const sidebarMobile = [
  {
    descripcion: "Unidad",
    posicion: 1,
    colorFondo: "",
    titulo: "UNIDAD",
    iconoWeb: <IconBox width={28} height={28} />,
    url: "",
  },
  {
    descripcion: "Reservas",
    posicion: 1,
    colorFondo: "",
    titulo: "RESERVAS",
    iconoWeb: <IconCalendar width={28} height={28} />,
    url: "/reservas",
  },
  {
    descripcion: "Reclamos",
    posicion: 1,
    colorFondo: "",
    titulo: "RECLAMOS",
    iconoWeb: <IconAlertTriangle width={28} height={28} />,
    url: "/reclamos",
  },
  {
    descripcion: "Pagos",
    posicion: 1,
    colorFondo: "",
    titulo: "PAGOS",
    iconoWeb: <IconReceipt width={28} height={28} />,
    url: "/pagos",
  },
  {
    descripcion: "Novedades",
    posicion: 1,
    colorFondo: "",
    titulo: "NOVEDADES",
    iconoWeb: <IconBell width={28} height={28} />,
    url: "/novedades",
  },
  {
    descripcion: "Juicios",
    posicion: 1,
    colorFondo: "",
    titulo: "JUICIOS",
    iconoWeb: <IconGavel width={28} height={28} />,
    url: "/juicios",
  },
  {
    descripcion: "Asambleas",
    posicion: 1,
    colorFondo: "",
    titulo: "ASAMBLEAS",
    iconoWeb: <IconUsers width={28} height={28} />,
    url: "/asambleas",
  },
  {
    descripcion: "Reglamento",
    posicion: 1,
    colorFondo: "",
    titulo: "REGLAMENTO",
    iconoWeb: <IconBook width={28} height={28} />,
    url: "/reglamento",
  },
  {
    descripcion: "Todas las unidades",
    posicion: 1,
    colorFondo: "",
    titulo: "TODAS LAS UNIDADES",
    iconoWeb: <IconPackages width={28} height={28} />,
    url: "/prp/expensas",
  },
];
