import {
  IconArticle,
  IconBell,
  IconBook,
  IconBox,
  IconGavel,
  IconHelpHexagon,
  IconLayout,
  IconLogout,
  IconPackages,
  IconReceipt2,
  IconUsers,
} from "@tabler/icons-react";

export const sidebar = {
  top: [
    {
      descripcion: "Unidad",
      posicion: 1,
      colorFondo: "",
      titulo: "UNIDAD",
      iconoWeb: <IconBox width={22} height={22} />,
      url: "",
    },
    {
      descripcion: "Novedades",
      posicion: 1,
      colorFondo: "",
      titulo: "NOVEDADES",
      iconoWeb: <IconBell width={22} height={22} />,
      url: "/novedades",
    },
    {
      descripcion: "Reclamos",
      posicion: 1,
      colorFondo: "",
      titulo: "RECLAMOS",
      iconoWeb: <IconArticle width={22} height={22} />,
      url: "/reclamos",
    },
    {
      descripcion: "Juicios",
      posicion: 1,
      colorFondo: "",
      titulo: "JUICIOS",
      iconoWeb: <IconGavel width={22} height={22} />,
      url: "/juicios",
    },
    {
      descripcion: "Asambleas",
      posicion: 1,
      colorFondo: "",
      titulo: "ASAMBLEAS",
      iconoWeb: <IconUsers width={22} height={22} />,
      url: "/asambleas",
    },
    {
      descripcion: "Reglamento",
      posicion: 1,
      colorFondo: "",
      titulo: "REGLAMENTO",
      iconoWeb: <IconBook width={22} height={22} />,
      url: "/reglamento",
    },
    {
      descripcion: "Todas las unidades",
      posicion: 1,
      colorFondo: "",
      titulo: "TODAS LAS UNIDADES",
      iconoWeb: <IconPackages width={22} height={22} />,
      url: "/prp/expensas",
    },
  ],
  // bottom: [
  //   {
  //     descripcion: "Ayuda",
  //     posicion: 1,
  //     colorFondo: "",
  //     titulo: "AYUDA",
  //     iconoWeb: <IconHelpHexagon width={22} height={22} />,
  //     url: "/ayuda",
  //   },
  //   {
  //     descripcion: "Desconectarse",
  //     posicion: 1,
  //     colorFondo: "",
  //     titulo: "LOGOUT",
  //     iconoWeb: <IconLogout width={22} height={22} />,
  //     url: "/sign-out",
  //   },
  // ],
};
