import type { Metadata } from "next";
import { GeistSans } from 'geist/font/sans'
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Consorcios en Red",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en"  className={`${GeistSans.variable}`}>
      <body className={inter.className} style={{ background: "#0a0a0a" }}>{children}</body>
    </html>
  );
}
