import type { Metadata, Viewport } from "next";
import { GeistSans } from 'geist/font/sans'
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Consorcios en Red",
  description: "Generated by create next app",
  category: "website",
  generator: "Next.js",
};

export const viewport: Viewport = {
  themeColor: "#FFFFFF",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="es" dir="ltr" className={`${GeistSans.variable}`} suppressHydrationWarning>
      <head>
        <script src="https://unpkg.com/react-scan/dist/auto.global.js" />
      </head>
      <body className={inter.className} style={{ background: "#0a0a0a" }} suppressHydrationWarning>
        {children}
      </body>
    </html>
  );
}
